### ISSUE TITLE
[C/decbin.c] Add binary to decimal conversion

### ISSUE THREAD

**Issue by Akharote1** [CSI-SPIT/hacktoberfest#12]
**Program Path:** c/decbin.c
**Requirement:** Add support for binary to decimal conversion into the program. Don't forget to add the prompt as well.
**Expected Output:**
```
What do want to convert?
1) Decimal to Binary
2) Binary to Decimal
2
Enter your number in binary:
101
The number in decimal is: 5
```

**Comment by rohanyrane** [comment]
please assign me
