### ISSUE TITLE
[Java/BankSystem.java] Check validity of username and password

### ISSUE THREAD

**Issue by Akharote1** [CSI-SPIT/hacktoberfest#14]
**Program Path:** java/BankSystem.java
**Issue:** Currently, username and password are not being validated when creating an account. Add a validation step before a user is created while checking the following:

Username:
- Between 3 and 15 characters (inclusive).
- Can contain only letters, numbers, and _.
- Cannot start with a number.
- Is case insensitive.
- Must not be taken by a previous user.

Password:
- Can only contain numbers, letters, and the following special characters: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
- Must be between 8 and 30 characters long (inclusive).
- Must contain at least one uppercase letter, one lowercase letter, one number, and one special character.

If the username and password do not fulfill these above requirements, print an error message.

Tip: A part of the above problem may be solved using Regular Expressions (Regex).

**Comment by prakhar-198** [comment]
Please assign me this I fixed last issue of this program I know the limitations,,,please assign me this one.
