### ISSUE TITLE
[C/ascii.c] Support for uppercase letters required

### ISSUE THREAD

**Issue by Akharote1** [CSI-SPIT/hacktoberfest#4]
**Program Path:** c/ascii.c
**Issue:**: The program currently only checks for lowercase characters. Make it so that uppercase letters print the same corresponding ASCII art (the upper and lowercase letters should print the same art).

**Comment by kashishvjain** [comment]
Can you assign me this?

**Comment by goldenPheonix02** [comment]
Can you assign this to me?
